trigger:
  - master

variables:
  imageName: 'pre-agendamiento-front'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: ApproveSQA
    displayName: Approve SQA
    jobs:
      - deployment: SQA
        displayName: Approve SQA
        environment: 'pre_agendamiento_SQA'
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceName'
              method: 'POST'
              headers: |
                {
                "PlanUrl": "$(system.CollectionUri)", 
                "ProjectId": "$(system.TeamProjectId)", 
                "HubName": "$(system.HostType)", 
                "PlanId": "$(system.PlanId)", 
                "JobId": "$(system.JobId)", 
                "TimelineId": "$(system.TimelineId)", 
                "TaskInstanceId": "$(system.TaskInstanceId)", 
                "AuthToken": "$(system.AccessToken)",
                "Authorization":"bearer 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",
                "Content-Type":"application/json"
                }
              body: '{
  "personalizations": [
    {
      "to": [
        {
          "email": "asantamariab@achs.cl",
          "name": "asantamariab"
        }
      ],
      "subject": "Paso a Produccion"
    }
  ],
  "from": {
    "email": "sel-devs@achs.cl",
    "name": "Agenda Sel"
  },
  "content": [
    {
      "type": "text/plain",
      "value": "Hello, World!"
    }
  ]
}'
              urlSuffix: 'https://api.sendgrid.com/v3/mail/send'
              waitForCompletion: 'false'
          - task: CmdLine@2
            inputs:
              script: |
                echo approved
                
                echo Hello world
          
  - stage: approveSPN
    dependsOn: ApproveSQA
    displayName: Approve SPN
    jobs:
      - deployment: SPN
        displayName: Approve SPN
        environment: 'pre_agendamiento_SPN'  
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: InvokeRESTAPI@1
            inputs:
              connectionType: 'connectedServiceNameARM'
              azureServiceConnection: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
              method: 'POST'
              body: '{body}'
              urlSuffix: 'url'
              waitForCompletion: 'false'
          
          - task: CmdLine@2
            inputs:
              script: |
                echo approved 2
  - stage: approveSPN2
    dependsOn: ApproveSQA
    displayName: Approve SPN 1
    jobs:
      - deployment: SPN
        displayName: Approve SPN
        environment: 'pre_agendamiento_SPN'  
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved 2
                
  
