trigger:
  - master

variables:
  imageName: 'pre-agendamiento-front'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Approve1
    displayName: Approve 1
    jobs:
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved
                
                echo Hello world
          
  - stage: approve2
    displayName: Approve 2
    jobs:
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved 2
                
  - stage: Build
    displayName: Build and Push
    jobs:
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            displayName: Build Dev image
            inputs:
              repository: $(imageName)
              command: buildAndPush
              Dockerfile: ./Dockerfile
              containerRegistry: preagendamiento-cr
              tags: '$(tag)'

  - stage: Deploy_Dev
    displayName: Deploy Dev
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
              appType: 'webAppContainer'
              WebAppName: 'dev-pre-agendamiento'
              DockerNamespace: 'preagendamiento.azurecr.io'
              DockerRepository: 'pre-agendamiento-front'
              DockerImageTag: '$(tag)'
  - stage: Deploy_QA
    displayName: Deploy QA
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'fake-env-for-approvals'
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
                    appType: 'webAppContainer'
                    WebAppName: 'qa-pre-agendamiento'
                    DockerNamespace: 'preagendamiento.azurecr.io'
                    DockerRepository: 'pre-agendamiento-front'
                    DockerImageTag: '$(tag)'
  - stage: Deploy_Staging
    displayName: Deploy Staging
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'fake-env-for-approvals'
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
                    appType: 'webAppContainer'
                    WebAppName: 'staging-pre-agendamiento'
                    DockerNamespace: 'preagendamiento.azurecr.io'
                    DockerRepository: 'pre-agendamiento-front'
                    DockerImageTag: '$(tag)'
  - stage: Deploy_Production
    displayName: Deploy Production
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: 'fake-env-for-approvals'
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureRmWebAppDeployment@4
                  inputs:
                    ConnectionType: 'AzureRM'
                    azureSubscription: 'Pre Agendamiento (ba10e75d-9812-4287-851a-a380629158f0)'
                    appType: 'webAppContainer'
                    WebAppName: 'pre-agendamiento-front'
                    DockerNamespace: 'preagendamiento.azurecr.io'
                    DockerRepository: 'pre-agendamiento-front'
                    DockerImageTag: '$(tag)'
