trigger:
  - master

variables:
  imageName: 'pre-agendamiento-front'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:        
  - stage: ApproveSQA
    displayName: Approve SQA
    jobs:
      - deployment: SQA
        displayName: Approve SQA
        environment: 'pre_agendamiento_SQA'
      - job:
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                curl --location --request POST 'https://api.sendgrid.com/v3/mail/send' \
                --header 'Authorization: bearer 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' \
                --header 'Content-Type: application/json' \
                --data-raw '{
                  "personalizations": [
                    {
                      "to": [
                        {
                          "email":"asantamariab@achs.cl",
                          "name":"asantamariab"
                        }
                      ],
                      "subject":"Paso a Produccion"
                    }
                  ],
                  "from": {
                    "email":"sel-devs@achs.cl",
                    "name":"Agenda Sel"
                  },
                  "content": [
                      {
                        "type": "text/plain",
                        "value": "Hello, World!"
                      }
                    ]
                }'
                
  
