trigger:
  - master

variables:
  imageName: 'pre-agendamiento-front'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: ApproveSQA
    displayName: Approve SQA
    jobs:
      - deployment: SQA
        displayName: Approve SQA
        environment: 'pre_agendamiento_SQA'
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved
                
                echo Hello world
          
  - stage: approveSPN
    dependsOn: ApproveSQA
    displayName: Approve SPN
    jobs:
      - deployment: SPN
        displayName: Approve SPN
        environment: 'pre_agendamiento_SPN'  
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved 2
  - stage: approveSPN2
    dependsOn: ApproveSQA
    displayName: Approve SPN 1
    jobs:
      - deployment: SPN
        displayName: Approve SPN
        environment: 'pre_agendamiento_SPN'  
      - job:
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                echo approved 2
                
  
