trigger:
  - master

variables:
  imageName: 'pre-agendamiento-front'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'
  bodyText: initialValue 

stages:        
  - stage: ApproveSQA
    displayName: Approve SQA
    jobs:
      - deployment: SQA
        displayName: Approve SQA
        environment: 'pre_agendamiento_SQA'
      - job:
        steps:
          - task: CmdLine@2
            inputs:
              script: |
                 echo ${{ variables.bodyText }} # outputs initialValue
          - task: CmdLine@2
            inputs:
              script: |
                 echo '##vso[task.setvariable variable=v]secondValue'
         